export enum MinistryMemberRole {
  KidsMinistryLeader = 'kids_ministry_leader',
  KidsMinistryCoLeader = 'kids_ministry_co_leader',
  KidsMinistryMember = 'kids_ministry_member',
  YouthMinistryLeader = 'youth_ministry_leader',
  YouthMinistryCoLeader = 'youth_ministry_co_leader',
  YouthMinistryMember = 'youth_ministry_member',
  IntercessionMinistryLeader = 'intercession_ministry_leader',
  IntercessionMinistryCoLeader = 'intercession_ministry_co_leader',
  IntercessionMinistryMember = 'intercession_ministry_member',
  EvangelismMinistryLeader = 'evangelism_ministry_leader',
  EvangelismMinistryCoLeader = 'evangelism_ministry_co_leader',
  EvangelismMinistryMember = 'evangelism_ministry_member',
  TechnologyMinistryLeader = 'technology_ministry_leader',
  TechnologyMinistryCoLeader = 'technology_ministry_co_leader',
  TechnologyMinistryMember = 'technology_ministry_member',
  DiscipleshipMinistryLeader = 'discipleship_ministry_leader',
  DiscipleshipMinistryCoLeader = 'discipleship_ministry_co_leader',
  DiscipleshipMinistryMember = 'discipleship_ministry_member',
  WorshipMinistryLeader = 'worship_ministry_leader',
  WorshipMinistryCoLeader = 'worship_ministry_co_leader',
  WorshipMinistryMember = 'worship_ministry_member',
}

export const MinistryMemberRoleNames: Record<MinistryMemberRole, string> = {
  [MinistryMemberRole.KidsMinistryLeader]: 'Min. Niños (Líder)',
  [MinistryMemberRole.KidsMinistryCoLeader]: 'Min. Niños (Co-Líder)',
  [MinistryMemberRole.KidsMinistryMember]: 'Min. Niños (Miembro)',
  [MinistryMemberRole.YouthMinistryLeader]: 'Min. Jóvenes (Líder)',
  [MinistryMemberRole.YouthMinistryCoLeader]: 'Min. Jóvenes (Co-Líder)',
  [MinistryMemberRole.YouthMinistryMember]: 'Min. Jóvenes (Miembro)',
  [MinistryMemberRole.IntercessionMinistryLeader]: 'Min. Intercesión (Líder)',
  [MinistryMemberRole.IntercessionMinistryCoLeader]:
    'Min. Intercesión (Co-Líder)',
  [MinistryMemberRole.IntercessionMinistryMember]: 'Min. Intercesión (Miembro)',
  [MinistryMemberRole.EvangelismMinistryLeader]: 'Min. Evangelismo (Líder)',
  [MinistryMemberRole.EvangelismMinistryCoLeader]:
    'Min. Evangelismo (Co-Líder)',
  [MinistryMemberRole.EvangelismMinistryMember]: 'Min. Evangelismo (Miembro)',
  [MinistryMemberRole.TechnologyMinistryLeader]: 'Min. Tecnología (Líder)',
  [MinistryMemberRole.TechnologyMinistryCoLeader]: 'Min. Tecnología (Co-Líder)',
  [MinistryMemberRole.TechnologyMinistryMember]: 'Min. Tecnología (Miembro)',
  [MinistryMemberRole.DiscipleshipMinistryLeader]: 'Min. Discipulado (Líder)',
  [MinistryMemberRole.DiscipleshipMinistryCoLeader]:
    'Min. Discipulado (Co-Líder)',
  [MinistryMemberRole.DiscipleshipMinistryMember]: 'Min. Discipulado (Miembro)',
  [MinistryMemberRole.WorshipMinistryLeader]: 'Min. Alabanza (Líder)',
  [MinistryMemberRole.WorshipMinistryCoLeader]: 'Min. Alabanza (Co-Líder)',
  [MinistryMemberRole.WorshipMinistryMember]: 'Min. Alabanza (Miembro)',
};
